// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqoNqHnZjlrC5gIIDIwxWKgmfESlzZra0',
    appId: '1:624677794434:web:dee8b94cdd50b2c626fa9b',
    messagingSenderId: '624677794434',
    projectId: 'trip-6debe',
    authDomain: 'trip-6debe.firebaseapp.com',
    storageBucket: 'trip-6debe.firebasestorage.app',
    measurementId: 'G-7PMVV5KEEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMsS_r52yApEafuEjzwTjhSK3fbVo7hw0',
    appId: '1:624677794434:android:ababfd137da733fa26fa9b',
    messagingSenderId: '624677794434',
    projectId: 'trip-6debe',
    storageBucket: 'trip-6debe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeAxeSQFCxS3ndiX6xC3oOyapcPtrKP6A',
    appId: '1:624677794434:ios:6fe0aa0b6fd5360626fa9b',
    messagingSenderId: '624677794434',
    projectId: 'trip-6debe',
    storageBucket: 'trip-6debe.firebasestorage.app',
    iosBundleId: 'com.example.trip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeAxeSQFCxS3ndiX6xC3oOyapcPtrKP6A',
    appId: '1:624677794434:ios:6fe0aa0b6fd5360626fa9b',
    messagingSenderId: '624677794434',
    projectId: 'trip-6debe',
    storageBucket: 'trip-6debe.firebasestorage.app',
    iosBundleId: 'com.example.trip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqoNqHnZjlrC5gIIDIwxWKgmfESlzZra0',
    appId: '1:624677794434:web:8d0c31cb07bc3a0f26fa9b',
    messagingSenderId: '624677794434',
    projectId: 'trip-6debe',
    authDomain: 'trip-6debe.firebaseapp.com',
    storageBucket: 'trip-6debe.firebasestorage.app',
    measurementId: 'G-PPDFXYFKY7',
  );
}
